### ISSUE TITLE
Add Kubescape to packages management for easier installation 

### ISSUE THREAD

**Issue by dwertent** [kubescape/kubescape#400] opened 2022-02-20 08:51 UTC
Songlin Jiang (@HollowMan6) is [an LFX mentee for the Kubescape project](https://mentorship.lfx.linuxfoundation.org/project/138e9cac-ec86-43cb-a04f-c2980e3c2865) for [Term 1 2023](https://github.com/cncf/mentoring/tree/main/lfx-mentorship/2023/01-Mar-May).

The primary goal is to ensure that when a new release is made in this repo, the most commonly used installation methods are available:

- Overall & `curl | bash`:
  - #195
  - #1015
- [Homebrew](https://brew.sh/) (_Working, with bugs:_)
  -  #1014
- [krew](https://krew.sigs.k8s.io/) (_Complete, with bugs:_)
  - #1112
- `apt`/`deb`, for Debian and Ubuntu (_New_)
  - #1143
- `yum`/`RPM`, for Red Hat and SUSE (_New_)
  - #1142

A second deliverable may include support for some other useful formats: 

- [Chocolatey](https://chocolatey.org/)
- [Scoop](https://scoop.sh/) 
- [nixpkgs](https://github.com/NixOS/nixpkgs)
- Any fixes required to the `kubescape` Docker container

The third phase will involve improvements to the Helm components, if time allows.

**Comment by avinashupadhya99** [comment] 2022-02-26 10:03
Isn't `brew` already supported in https://github.com/armosec/homebrew-kubescape ?

**Comment by dwertent** [comment] 2022-02-27 07:35
@avinashupadhya99 It is, but we are having issues with it [as you noticed](https://github.com/armosec/kubescape/issues/417) 😏

**Comment by Atharva-Shinde** [comment] 2022-02-27 10:37
@dwertent I'm down to fix this issue. So, what exactly needs to be done to fix this and where could I possibly start?

**Comment by 9gl** [comment] 2022-08-22 17:08
Hi @dwertent ,
I'm interested in contributing to this issue, so before I start working
it, would you mind sparing your time explaining what the issue is about and pointing me to some resources to get started.

**Comment by RahulSurwade08** [comment] 2022-08-25 22:46
Hey @dwertent , I am interested to contribute in this issue. How can i get started?

**Comment by ryuusama09** [comment] 2022-08-27 02:59
hi @dwertent , I want to fix this issue, please tell me where exactly can i start from and what needs to be possibly done ?

**Comment by Csrivastava003** [comment] 2022-09-01 15:50
Hey, I would like to work on this issue!

**Comment by craigbox** [comment] 2023-01-09 06:21
Thank you to everyone who has expressed an interest in packaging kubescape. 

[Homebrew support is underway again](https://github.com/kubescape/kubescape/issues/1014), so the outstanding actions are Debian and Red Hat packages.

If you're interested in getting started, please look at:

- [Debian Packaging For The Modern Developer](https://github.com/FooBarWidget/debian-packaging-for-the-modern-developer)
- [RPM Packaging Guide](https://rpm-packaging-guide.github.io/)

If you're interested in contributing either package, please create an issue and link back to this one.  I'll link your issue to the description.

**Comment by 0saurabh0** [comment] 2023-02-06 08:58
Hi @craigbox I'm very interesting on working on this issue as previously, I've worked with bash scripts.
I do have one question though, are the RPM and DEB packages going to be GitHub release?

**Comment by craigbox** [comment] 2023-02-06 09:09
This issue is being submitted for the 2023 Mar-May [LFX Mentorship program](https://github.com/cncf/mentoring/tree/main/lfx-mentorship). 

We've specified an end state.  It will be up to the mentee selected for the project to come up with the design proposal on how to get there!  The integration would definitely be with our current release pipeline which is driven by GitHub.

**Comment by 0saurabh0** [comment] 2023-02-06 10:04
I'm aware that it's being submitted for the mentorship program that's where I got to know about this and definitely wil submit the application for this one.

**Comment by HollowMan6** [comment] 2023-02-10 12:57
Hi community! I would like to apply for the 2023 Mar-May [LFX Mentorship program](https://github.com/cncf/mentoring/tree/main/lfx-mentorship) to resolve this issue. I have completed my initial investigation and here's my proposal. Any feedback is welcomed.

For demoing, I have tried packaging both the rpm and the debian packages by directly using the binary from kubescape-ubuntu-latest.tar.gz. Here's the [packaging scripts source code](https://github.com/HollowMan6/kubescape-deb-rpm) I have also written a GitHub Actions workflow for automating the whole process, you can [get the build artifacts here](https://github.com/HollowMan6/kubescape-deb-rpm/actions/runs/4143706022).

For distributing the packages, of course we can build that manually just like [one of my previous project](https://github.com/openSUSE/Customize-IBus/tree/package-repo). However, I would highly recommend openSUSE's open build service (OBS), I have also [created a demo](https://build.opensuse.org/package/show/home:hollowman/kubescape). OBS allows easily distribution of the packages, users can add repository according to the [guide here](https://software.opensuse.org//download.html?project=home%3Ahollowman&package=kubescape), then the Linux package manager in their system will make sure that users can get the update easily.

The work I would be doing during the mentorship will include adding tests to ensure the packaging is OK. Of course I will change the packaging workflow into building from source code instead of directly grab the binary file, so more architectures can get supported. I would also intergrate the OBS repository update feature (automate `osc addremove *; osc commit`) into workflow. Finally I will integrat the [GitHub Actions workflow](https://github.com/HollowMan6/kubescape-deb-rpm/blob/main/.github/workflows/build.yml) into the release workflow of kubescape.

Thank you!

**Comment by 0saurabh0** [comment] 2023-02-10 14:24
@HollowMan6 I think you have to propose all of that in your application.

**Comment by HollowMan6** [comment] 2023-02-10 14:26
> @HollowMan6 I think you have to propose all of that in your application.

Yes, I will. I post here just to receive feedback, like if there're any potential things that I didn't cover.

**Comment by craigbox** [comment] 2023-02-12 23:21
(For the record, every time I see your handle I sing [this song](https://www.youtube.com/watch?v=En6iGamLwso) in my head 😊)

That seems like a good scope of work, and depending on how quickly it was completed, I would look to applying similar rigour to platforms such as Nix, krew, and our client container (used by a GitHub action to run Kubescape).

**Comment by HollowMan6** [comment] 2023-02-13 08:49
Thank you for your feedback! I think I can manage to add kubescape to platforms such as Nix, krew, and also the client container with similar rigour. I have experience maintaining [several nixpkgs](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+author%3A%40me+is%3Aclosed) as well, and I would only need to figure out how to add kubescape into krew when all the others are completed. Looking forward to working with you!

**Comment by matthyx** [comment] 2023-02-13 08:56
Krew is already being handled. Thanks for your help!

**Comment by HollowMan6** [comment] 2023-02-13 10:52
> I would look to applying similar rigour to platforms such as Nix, krew, and our client container (used by a GitHub action to run Kubescape)

I can see that actually kubescape is already [available in nixpkgs](https://github.com/NixOS/nixpkgs/blob/82b4c24705340bceed0d463d3d897b6ebcbd7550/pkgs/tools/security/kubescape/default.nix#L8). Then just as mentioned, krew has already been handled, the docker container is also [available](https://github.com/kubescape/kubescape/blob/2ba3f78bfc8c6563ae151762fb2b79eba3433307/build/Dockerfile ), I will try my best to see if there are any room for improvement once the rpm and deb work have been completed as proposed.

**Comment by HollowMan6** [comment] 2023-08-02 12:54
Let's close this as everything mentioned on this issue is done, and I have graduated from LFX. 😊

**Closed by HollowMan6** 2023-08-02 12:54 UTC
Labels: feature
