### ISSUE TITLE
Parameter `accessKey` is required to connect to armosec.io dashboard (and not `access-key`)

### ISSUE THREAD

**Issue by ioannisgk** [kubescape/kubescape#1595] opened 2024-01-31 21:48 UTC
# Description
With the default instructions, Kubescape cannot connect to armosec.io dashboard, it requires an access key.
The `access-key` variable name in the helm chart values needs to be updated to `accessKey` in order for the connection to be successful.

# Environment
Cluster: Kubernetes cluster with Ubuntu 22.04
Version: [Helm chart v1.18.1](https://artifacthub.io/packages/helm/kubescape/kubescape-operator)
 
# Steps To Reproduce
1. Have a fresh Kubernetess cluster with Ubuntu 22.04
2. Deploy Argo CD and setup a GitOps repository
3. Create an Argo CD application yaml file and use this info: targetRevision: 1.18.1, chart: kubescape-operator
5. Add the `account` and `server` parameters names and values
6. Get an error that the access key is not defined

# Expected behavior
According to the official instructions [here](https://cloud.armosec.io/dashboard?addCluster=verify), we see the parameters required for the helm chart:

`helm repo add kubescape https://kubescape.github.io/helm-charts/ ; helm repo update ; helm upgrade --install kubescape kubescape/kubescape-operator -n kubescape --create-namespace --set clusterName=`kubectl config current-context` --set account=6f488322-0146-4d79-b7ee-2eeb93cb5915 --set server=api.armosec.io`

So, for Kubescape to be able to connect to the dashboard, I need to specify:
- account
- server

# Actual Behavior
After applying the Argo CD yaml file for the Kubescape helm chart v.1.18.1, I see this error:
`Error: execution error at (kubescape-operator/templates/synchronizer/serviceaccount.yaml:1:29):
submitting is enabled but value for accessKey is not defined: To obtain an access key,
go to 'Settings' -> 'Agent Access Keys' at https://cloud.armosec.io and
re-run with --set accessKey=<your key> Use --debug flag to render out invalid YAML`

# Additional context
In order to solve this, I followed what the error message said:
- Created an access key from the armosec.io dashboard
- Added one more parameter as part of the helm chart, the parameter name was `accessKey` and not `access-key`, which is mentioned in the default values [here](https://artifacthub.io/packages/helm/kubescape/kubescape-operator?modal=values&path=access-key).

I think 2 actions need to be done:
1. Update the instructions with the command and the parameters needed to connect Kubescape to the armosec.io dashboard, and make sure to include the `accessKey` parameter [here](https://cloud.armosec.io/dashboard?addCluster=verify) (this parameter is currently missing)
2. Update the default values section (in the helm chart description page), with the correct parameter name to be `accessKey` instead of `access-key` [here](https://artifacthub.io/packages/helm/kubescape/kubescape-operator?modal=values&path=access-key).

**Comment by amirmalka** [comment] 2024-02-01 08:17
HI @ioannisgk,

Thanks for raising this issue. 

We have opened a PR to fix the access key parameters in the values file. (https://github.com/kubescape/helm-charts/pull/387)

As for the first issue, we'd like to have a session with you if possible so we can understand why it happens since it was not reproduced when I checked it.

**Comment by amirmalka** [comment] 2024-02-01 10:00
@ioannisgk 

After checking with engineering team we might have a better understand of the issue. For each user which signs up an access key should be generated by default but for your account this was not the case, and that would be the reason for the missing access key in the command that showed up in the UI.
We have recently fixed a bug in the ARMO platform related to access key generation but it only applies for new sign ups.

A few questions:
- Did you sign up for the ARMO platform recently? If not, when (approximately)?
- Did you encounters any errors during sign up?
- Did you connect your cluster right after signing up?

**Comment by ioannisgk** [comment] 2024-02-02 08:19
@amirmalka 

Thank you for the explanation. Regarding your questions:
- I signed up for ARMO on 23rd of November 2023
- I encountered no errors during sign up
- After signing up, I used only the `account` parameter and I could see all the data in ARMO platform (the connection to the cluster was successful)

A few days ago I used the Helm chart v1.18.1 and I saw the error, thus finding out that I had to use the `accessKey` parameter to make the connection work.

**Comment by amirmalka** [comment] 2024-02-12 15:34
Thanks @ioannisgk 
The bug has been solved in ARMO platform and a new helm chart was released with the fix for the access key value.

**Closed by amirmalka** 2024-02-12 15:34 UTC
Labels: bug
