### ISSUE TITLE
advanced filtering for resources to be scanned/excluded/included

### ISSUE THREAD

**Issue by RiccardoBoettcher** [kubescape/kubescape#1289] opened 2023-07-21 12:06 UTC
## Overview
Kubernetes namespace can be excluded by individual names with the "--exclude-namespace" argument.

## Problem
In a cluster running Rancher (https://www.rancher.com) a massive amount of namespaces, users, groups and other resources is created for the data hold and used by Rancher. Rancher basically uses kubernetes resources as state storage.
Scanning all the resources leads to overloading kubescape and crashes or OOM errors.

Rancher creates:
* namespaces
   * c-xxxx
   * p-xxxx
   * u-xxxx
* users: u-xxxx
* groups: g-xxxx
Where xxxx are arbitrary ids generate by rancher.

## Solution
* add advanced filters for the --exclude-namespace option, either simple * star matchers or regexes
* additional filters for users and groups (also using advanced matching)
* or allow reading the filters from external files, so that the filtering can  be implemented externally

## Alternatives
Try to find the reason  from the crashes/OOM errors when scanning a cluster running the rancher cluster manager.

**Comment by XDRAGON2002** [comment] 2023-07-21 12:19
Hi @RiccardoBoettcher!
Have you taken a look at [this](https://github.com/kubescape/kubescape/tree/master/examples/exceptions)?

Since this is the preferred method to exempt certain resources from Kubescape.

**Comment by RiccardoBoettcher** [comment] 2023-07-21 12:34
The problem I faces seems already happen during the scanning phase. Something is special with the Rancher managed resources which brings kubescape down...

A workaround:
```bash
kubescape scan --exclude-namespaces $(kubectl get ns  --no-headers -o custom-columns=":metadata.name" | grep -iE '[puc]-.*' | paste -d , -s -)
```

Using the exemptions as suggested, would be possible. Seems regexes are supported, so could be used to filter out rancher stuff. But, depends on point of time the filtering happens. If it still brings kubescape down...

Having an easy way to exclude resources from being scanned in the first place might be better.

**Comment by XDRAGON2002** [comment] 2023-07-21 13:46
@RiccardoBoettcher If the problem is with the scan itself then the exclude option we allow right now will not be of much help as it acts after the scan is essentially completed.

The ability to exempt resources from even being scanned in the first place would probably be a hefty breaking change I believe. Though it would actually be more useful than to simply "masquerade" the output.

@craigbox @slashben @RiccardoBoettcher and members of the official team might be better of in taking this decision, though I believe it would be a much useful change if proceeded with.

In the meantime could you maybe procure some logs or try to pinpoint exactly due to what resources Kubescape ends up crashing? Maybe provide a minimal reproducible example?

**Comment by RiccardoBoettcher** [comment] 2023-07-21 14:56
I can't say which of the resources exactly makes the trouble, but could at least narrow the scope to the `p-xxxx` namespaces (-> rancher projects)

One example of such a resource (not necessarily the one triggering the trouble):
```yaml
apiVersion: v1                                                                                                                                                                                                          
kind: Namespace                                                                                                                                                                                                         
metadata:                                                                                                                                                                                                               
  annotations:                                                                                                                                                                                                          
    cattle.io/status: '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2022-04-19T15:13:36Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2
022-04-19T15:13:36Z"}]}'                                                                                                                                                                                                
    field.cattle.io/projectId: local:p-mwkz7                                                                                                                                                                            
    lifecycle.cattle.io/create.namespace-auth: "true"                                                                                                                                                                   
    management.cattle.io/no-default-sa-token: "true"                                                                                                                                                                    
    management.cattle.io/system-namespace: "true"                                                                                                                                                                       
  creationTimestamp: "2022-04-19T15:13:35Z"                                                                                                                                                                             
  finalizers:                                                                                                                                                                                                           
  - controller.cattle.io/namespace-auth                                                                                                                                                                                 
  labels:                                                                                                                                                                                                               
    field.cattle.io/projectId: p-mwkz7                                                                                                                                                                                  
    kubernetes.io/metadata.name: p-4prwb                                                                                                                                                                                
  name: p-4prwb                                                                                                                                                                                                         
  resourceVersion: "471751568"                                                                                                                                                                                          
  uid: 68f0fc1f-4c86-4b2f-80b1-f33352da0e79                                                                                                                                                                             
spec:                                                                                                                                                                                                                   
  finalizers:                                                                                                                                                                                                           
  - kubernetes                                                                                                                                                                                                          
status:                                                                                                                                                                                                                 
  phase: Active  
```

And the referenced `p-mwkz7':
```yaml
apiVersion: v1                                                                                                                                                                                                          
kind: Namespace                                                                                                                                                                                                         
metadata:                                                                                                                                                                                                               
  annotations:                                                                                                                                                                                                          
    cattle.io/status: '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2022-04-19T18:38:32Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2
022-04-19T18:38:32Z"}]}'                                                                                                                                                                                                
    field.cattle.io/projectId: local:p-mwkz7                                                                                                                                                                            
    lifecycle.cattle.io/create.namespace-auth: "true"                                                                                                                                                                   
    management.cattle.io/no-default-sa-token: "true"                                                                                                                                                                    
    management.cattle.io/system-namespace: "true"                                                                                                                                                                       
  creationTimestamp: "2022-04-19T18:38:31Z"                                                                                                                                                                             
  finalizers:                                                                                                                                                                                                           
  - controller.cattle.io/namespace-auth                                                                                                                                                                                 
  labels:                                                                                                                                                                                                               
    field.cattle.io/projectId: p-mwkz7                                                                                                                                                                                  
    kubernetes.io/metadata.name: p-mwkz7                                                                                                                                                                                
  name: p-mwkz7                                                                                                                                                                                                         
  resourceVersion: "471751733"                                                                                                                                                                                          
  uid: e216ac02-243f-4880-9198-73b0e144de30                                                                                                                                                                             
spec:                                                                                                                                                                                                                   
  finalizers:                                                                                                                                                                                                           
  - kubernetes                                                                                                                                                                                                          
status:                                                                                                                                                                                                                 
  phase: Active                                                                                                                                                                                                         
```

**Comment by RiccardoBoettcher** [comment] 2023-07-21 14:58
Exception log
``` 
kubescape scan --exclude-namespaces $(kubectl get ns  --no-headers -o custom-columns=":metadata.name" | grep -viE '[p]-.*' | paste -d , -s -)
[info] Kubescape scanner starting
I0721 16:50:16.156830    8605 request.go:682] Waited for 1.039030843s due to client-side throttling, not priority and fairness, request: GET:https://xxxxxxxxxxx.eu-central-1.eks.amazonaws.com/apis/litmuschaos.io/v1alpha1?timeout=32s
[info] Downloading/Loading policy definitions
[success] Downloaded/Loaded policy
[info] Accessing Kubernetes objects
[success] Accessed to Kubernetes objects
[info] Scanning. Cluster: xxxxxx
◑fatal error: runtime: out of memory

runtime stack:
runtime.throw({0x557b2bea2d82?, 0x0?})
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/panic.go:1047 +0x5f fp=0x7f5cf2ffcca0 sp=0x7f5cf2ffcc70 pc=0x557b291e69bf
runtime.sysMapOS(0xc3a4400000, 0x400000?)
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mem_linux.go:187 +0x11b fp=0x7f5cf2ffcce8 sp=0x7f5cf2ffcca0 pc=0x557b291c62db
runtime.sysMap(0x7f5cf2ffcd80?, 0x557b291db3da?, 0x557b2ef48da8?)
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mem.go:142 +0x35 fp=0x7f5cf2ffcd18 sp=0x7f5cf2ffcce8 pc=0x557b291c5cb5
runtime.(*mheap).grow(0x557b2ef48da0, 0x2000?)
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mheap.go:1522 +0x252 fp=0x7f5cf2ffcd90 sp=0x7f5cf2ffcd18 pc=0x557b291d6792
runtime.(*mheap).allocSpan(0x557b2ef48da0, 0x1, 0x0, 0xb7?)
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mheap.go:1243 +0x1b7 fp=0x7f5cf2ffce28 sp=0x7f5cf2ffcd90 pc=0x557b291d5eb7
runtime.(*mheap).alloc.func1()
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mheap.go:961 +0x65 fp=0x7f5cf2ffce70 sp=0x7f5cf2ffce28 pc=0x557b291d5965
runtime.systemstack()
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/asm_amd64.s:496 +0x46 fp=0x7f5cf2ffce78 sp=0x7f5cf2ffce70 pc=0x557b2921bc86

goroutine 422 [running]:
runtime.systemstack_switch()
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/asm_amd64.s:463 fp=0xc085f731b0 sp=0xc085f731a8 pc=0x557b2921bc20
runtime.(*mheap).alloc(0x557b291dff70?, 0x0?, 0x9b?)
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mheap.go:955 +0x65 fp=0xc085f731f8 sp=0xc085f731b0 pc=0x557b291d58a5
runtime.(*mcentral).grow(0x2000?)
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mcentral.go:246 +0x57 fp=0xc085f73238 sp=0xc085f731f8 pc=0x557b291c5617
runtime.(*mcentral).cacheSpan(0x557b2ef59738)
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mcentral.go:166 +0x306 fp=0xc085f73290 sp=0xc085f73238 pc=0x557b291c5466
runtime.(*mcache).refill(0x7f5d29b08f18, 0xa?)
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mcache.go:182 +0x152 fp=0xc085f732d0 sp=0xc085f73290 pc=0x557b291c4bb2
runtime.(*mcache).nextFree(0x7f5d29b08f18, 0xa)
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/malloc.go:855 +0x85 fp=0xc085f73318 sp=0xc085f732d0 pc=0x557b291bae25
runtime.mallocgc(0x28, 0x557b2cca8ba0, 0x1)
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/malloc.go:1042 +0x455 fp=0xc085f73380 sp=0xc085f73318 pc=0x557b291bb415
runtime.newobject(0x557b2c9f9a40?)
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/malloc.go:1254 +0x27 fp=0xc085f733a8 sp=0xc085f73380 pc=0x557b291bb9a7
github.com/open-policy-agent/opa/ast.NewTerm(...)
        /home/runner/go/pkg/mod/github.com/open-policy-agent/opa@v0.52.0/ast/term.go:302
github.com/open-policy-agent/opa/ast.InterfaceToValue({0x557b2c9f9a40?, 0xc159a45710?})
        /home/runner/go/pkg/mod/github.com/open-policy-agent/opa@v0.52.0/ast/term.go:95 +0x8f5 fp=0xc085f735a8 sp=0xc085f733a8 pc=0x557b2ad47d15
github.com/open-policy-agent/opa/ast.InterfaceToValue({0x557b2c9f9a40?, 0xc159a456e0?})
        /home/runner/go/pkg/mod/github.com/open-policy-agent/opa@v0.52.0/ast/term.go:91 +0x8d0 fp=0xc085f737a8 sp=0xc085f735a8 pc=0x557b2ad47cf0
github.com/open-policy-agent/opa/ast.InterfaceToValue({0x557b2c9f9a40?, 0xc159a456b0?})
        /home/runner/go/pkg/mod/github.com/open-policy-agent/opa@v0.52.0/ast/term.go:91 +0x8d0 fp=0xc085f739a8 sp=0xc085f737a8 pc=0x557b2ad47cf0
github.com/open-policy-agent/opa/ast.InterfaceToValue({0x557b2c9f9a40?, 0xc159a45680?})
        /home/runner/go/pkg/mod/github.com/open-policy-agent/opa@v0.52.0/ast/term.go:91 +0x8d0 fp=0xc085f73ba8 sp=0xc085f739a8 pc=0x557b2ad47cf0
github.com/open-policy-agent/opa/ast.InterfaceToValue({0x557b2c7c6d60?, 0xc159a412a8?})
        /home/runner/go/pkg/mod/github.com/open-policy-agent/opa@v0.52.0/ast/term.go:77 +0xa05 fp=0xc085f73da8 sp=0xc085f73ba8 pc=0x557b2ad47e25
github.com/open-policy-agent/opa/ast.InterfaceToValue({0x557b2c9f9a40?, 0xc159a45620?})
        /home/runner/go/pkg/mod/github.com/open-policy-agent/opa@v0.52.0/ast/term.go:91 +0x8d0 fp=0xc085f73fa8 sp=0xc085f73da8 pc=0x557b2ad47cf0
github.com/open-policy-agent/opa/ast.InterfaceToValue({0x557b2c9f9a40?, 0xc159a455f0?})
        /home/runner/go/pkg/mod/github.com/open-policy-agent/opa@v0.52.0/ast/term.go:91 +0x8d0 fp=0xc085f741a8 sp=0xc085f73fa8 pc=0x557b2ad47cf0
github.com/open-policy-agent/opa/ast.InterfaceToValue({0x557b2c7c6d60?, 0xc159a41758?})
        /home/runner/go/pkg/mod/github.com/open-policy-agent/opa@v0.52.0/ast/term.go:77 +0xa05 fp=0xc085f743a8 sp=0xc085f741a8 pc=0x557b2ad47e25
github.com/open-policy-agent/opa/ast.InterfaceToValue({0x557b2c9f9a40?, 0xc159a455c0?})
        /home/runner/go/pkg/mod/github.com/open-policy-agent/opa@v0.52.0/ast/term.go:91 +0x8d0 fp=0xc085f745a8 sp=0xc085f743a8 pc=0x557b2ad47cf0
github.com/open-policy-agent/opa/ast.InterfaceToValue({0x557b2c7c6d60?, 0xc303d2acc0?})
        /home/runner/go/pkg/mod/github.com/open-policy-agent/opa@v0.52.0/ast/term.go:77 +0xa05 fp=0xc085f747a8 sp=0xc085f745a8 pc=0x557b2ad47e25
github.com/open-policy-agent/opa/rego.(*Rego).parseRawInput(0x0?, 0xc03b4e8f30, {0x557b2d051af0, 0xc03b4dcda0})
        /home/runner/go/pkg/mod/github.com/open-policy-agent/opa@v0.52.0/rego/rego.go:1828 +0x14d fp=0xc085f74820 sp=0xc085f747a8 pc=0x557b2aeffe4d
github.com/open-policy-agent/opa/rego.(*Rego).parseInput(0xc03b4d4da8?)
        /home/runner/go/pkg/mod/github.com/open-policy-agent/opa@v0.52.0/rego/rego.go:1807 +0x4f fp=0xc085f74850 sp=0xc085f74820 pc=0x557b2aeffccf
github.com/open-policy-agent/opa/rego.(*Rego).prepare(0xc0011a7500, {0x557b2d048780, 0xc000144960}, 0x557b2cfffcc0?, {0xc085f74a40, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/open-policy-agent/opa@v0.52.0/rego/rego.go:1639 +0x65 fp=0xc085f74918 sp=0xc085f74850 pc=0x557b2aefe585
github.com/open-policy-agent/opa/rego.(*Rego).PrepareForEval(0xc0011a7500, {0x557b2d048780, 0xc000144960}, {0x0, 0x0, 0x557b2acc9f45?})
        /home/runner/go/pkg/mod/github.com/open-policy-agent/opa@v0.52.0/rego/rego.go:1529 +0x538 fp=0xc085f75198 sp=0xc085f74918 pc=0x557b2aefdab8
github.com/open-policy-agent/opa/rego.(*Rego).Eval(0xc0011a7500, {0x557b2d048780, 0xc000144960})
        /home/runner/go/pkg/mod/github.com/open-policy-agent/opa@v0.52.0/rego/rego.go:1203 +0xb0 fp=0xc085f75370 sp=0xc085f75198 pc=0x557b2aefa650
github.com/kubescape/kubescape/v2/core/pkg/opaprocessor.(*OPAProcessor).regoEval(0x557b2c9f9a40?, {0x557b2d048780, 0xc000144960}, {0xc023ebc000, 0xc297, 0xd800}, 0x0?, 0xc03ab594e0)
        /home/runner/work/kubescape/kubescape/core/pkg/opaprocessor/processorhandler.go:396 +0x1bd fp=0xc085f75428 sp=0xc085f75370 pc=0x557b2bd43b3d
github.com/kubescape/kubescape/v2/core/pkg/opaprocessor.(*OPAProcessor).runRegoOnK8s(0xc001fe6480, {0x557b2d048780, 0xc000144960}, 0xc0010b6a00, {0xc023ebc000, 0xc297, 0xd800}, 0x557b2cffcab0, {{0x0, 0x0}, ...})
        /home/runner/work/kubescape/kubescape/core/pkg/opaprocessor/processorhandler.go:379 +0x33f fp=0xc085f75520 sp=0xc085f75428 pc=0x557b2bd4375f
github.com/kubescape/kubescape/v2/core/pkg/opaprocessor.(*OPAProcessor).runOPAOnSingleRule(0xc001fe6480?, {0x557b2d048780?, 0xc000144960?}, 0xc0012806e8?, {0xc023ebc000?, 0xc0011fc000?, 0x557b292a4852?}, 0xc001280700?, {{0x0, 0x0}, ...})
        /home/runner/work/kubescape/kubescape/core/pkg/opaprocessor/processorhandler.go:346 +0x88 fp=0xc085f75620 sp=0xc085f75520 pc=0x557b2bd432c8
github.com/kubescape/kubescape/v2/core/pkg/opaprocessor.(*OPAProcessor).processRule(0xc001fe6480, {0x557b2d048780, 0xc000144960}, 0xc0010b6a00, 0xc001280b08?)
        /home/runner/work/kubescape/kubescape/core/pkg/opaprocessor/processorhandler.go:305 +0x537 fp=0xc085f75a30 sp=0xc085f75620 pc=0x557b2bd429f7
github.com/kubescape/kubescape/v2/core/pkg/opaprocessor.(*OPAProcessor).processControl(0xc001fe6480, {0x557b2d048780, 0xc000144960}, 0xc0021d36c0)
        /home/runner/work/kubescape/kubescape/core/pkg/opaprocessor/processorhandler.go:230 +0x133 fp=0xc085f75eb8 sp=0xc085f75a30 pc=0x557b2bd41ed3
github.com/kubescape/kubescape/v2/core/pkg/opaprocessor.(*OPAProcessor).Process.func2()
        /home/runner/work/kubescape/kubescape/core/pkg/opaprocessor/processorhandler.go:167 +0x4e fp=0xc085f75f78 sp=0xc085f75eb8 pc=0x557b2bd40cae
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64 fp=0xc085f75fe0 sp=0xc085f75f78 pc=0x557b2b9d94c4
runtime.goexit()
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc085f75fe8 sp=0xc085f75fe0 pc=0x557b2921dec1
created by golang.org/x/sync/errgroup.(*Group).Go
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
... 
output shortend
...
```

**Comment by XDRAGON2002** [comment] 2023-07-21 17:42
Based on the exception log, [this](https://github.com/kubescape/kubescape/blob/master/core/pkg/opaprocessor/processorhandler.go#L396) seems to be where the problem is happening. At a glance I don't see anything wrong with it.

It also says there was an Out Of Memory (OOM) error, could you once while running the tool keep a track of the memory usage of your system? Also how many resources would probably be present in the cluster Kubescape is trying to scan?

Maybe loading an astronomically large number of resources in the cluster to memory as well as due to the caching being utilized in some places could lead to this?

**Comment by XDRAGON2002** [comment] 2023-07-21 18:15
@craigbox @slashben @vladklokun @alegrey91 might be better off making a comment regarding probable causes on this than me I believe.

**Comment by RiccardoBoettcher** [comment] 2023-07-24 06:28
@XDRAGON2002: There are around 70 of the "p-xxxx" namespaces. So not really much.

**Comment by XDRAGON2002** [comment] 2023-07-25 09:19
@RiccardoBoettcher interesting, I to be honest cannot pinpoint what might be the cause here, though at this point I believe someone from the core team might be more well versed to help you out here, but I'll still try and figure out what might be the cause of this.

Thanks!

**Comment by dwertent** [comment] 2023-09-01 05:24
Thanks for reporting. 
This panic has been fixed in the last release.

Regarding the kubescape pod OOM, we made some major optimizations in memory usage so you should no longer face such difficulties :)

**Closed by dwertent** 2023-09-01 05:24 UTC
Labels: feature
