### ISSUE TITLE
Exception on label is ignored with a resource that has multiple labels

### ISSUE THREAD

**Issue by martijnvdp** [kubescape/kubescape#1278] opened 2023-07-12 09:53 UTC
# Description
Exception on label is ignored with a resource that has multiple labels

# Environment
OS: ` UBUNTU 22.04` 
Version: ` v2.3.7` 
 
# Steps To Reproduce

1. create a resource.yaml with a resource to scan with errors like
```
apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
  labels:
    another-label: test
    exclude-from-kubescape: yes
```
2. scan the file which should result in 2 failures
kubescape scan resource.yaml --verbose --format junit 
 | Medium   | Cluster internal networking | https://hub.armosec.io/docs/c-0054 |                      |
 | Low      | Network mapping             | https://hub.armosec.io/docs/c-0049 |
3. then i try to create an exception based on the label in a new json file exception.json
```
  {
    "name": "exclude-test",
    "policyType": "postureExceptionPolicy",
    "actions": ["alertOnly"],
    "resources": [
      {
        "designatorType": "Attributes",
        "attributes": {
          "exclude-from-kubescape": "yes"
        }
      }
    ],
    "posturePolicies": [
      {
        "controlID": "C-0054"
      },
      {
        "controlID": "C-0049"
      }
    ]
  }
  ```
4. rescan using this json gives same result 2 failures:
 `kubescape scan resource.yaml --verbose --format junit --exceptions .\exception.json`
5. remove one label from the resource yaml so it only has the exception label and save
```
apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
  labels:
    exclude-from-kubescape: yes
```
6. than i do a rescan `kubescape scan resource.yaml --verbose --format junit --exceptions .\exception.json`
and its excluded correctly
    

# Expected behavior
i expected to be able to exclude the resource when it has also other labels than the exception label
the examples indicate that this should work https://github.com/kubescape/kubescape/tree/master/examples/exceptions
# Actual Behavior
exception only seems to work when the resource only has 1 exception label

**Comment by XDRAGON2002** [comment] 2023-07-12 11:26
Hi @martijnvdp!
I've been able to replicate this behavior locally, I even tried some other combinations such as:
n labels <-> n exceptions = doesn't work
n labels <-> 1 exception = doesn't work
1 label <-> n exceptions = doesn't work
1 label <-> 1 exception = works

I guess @craigbox @slashben might be able to shed some light on this if whether this is intended behavior or actually a bug (which it actually seems?)

In case of a bug, we'd have to think if we want to enable "OR" between the labels or "AND" instead. This is a very basic matching method, but we could even go with a more sophisticated and powerful method if need be for more fine grained control.

Thoughts?

**Comment by XDRAGON2002** [comment] 2023-07-20 10:44
@martijnvdp kindly do take a look at the PR I've linked above, it contains the fix for this as well as defines how a user can now make powerful custom conditional matches.

Thanks!

**Comment by martijnvdp** [comment] 2023-07-21 07:34
thanks @XDRAGON2002 will take a look, i see its in another repo, maybe its also reproducable by adding a test case in https://github.com/kubescape/opa-utils/blob/master/exceptions/exceptionprocessor_test.go than

**Comment by martijnvdp** [comment] 2023-07-24 10:15
like this test is failing, https://github.com/kubescape/opa-utils/pull/126/files
but with your pr it is fixed

**Closed** 2023-08-01 04:59 UTC
Labels: bug
